### Importing the Packages

In [66]:
import pandas as pd
import numpy as np

### Importing the data

In [40]:
raw_csv_data = pd.read_csv("D:/Study/data_science/Time Series Forecasting/datasets/Section 3/Index2018.csv") 
df_comp=raw_csv_data.copy()

In [41]:
df_comp.head()

         date     spx      dax     ftse    nikkei
0  07/01/1994  469.90  2224.95  3445.98  18124.01
1  10/01/1994  475.27  2225.00  3440.58  18443.44
2  11/01/1994  474.13  2228.10  3413.77  18485.25
3  12/01/1994  474.17  2182.06  3372.02  18793.88
4  13/01/1994  472.47  2142.37  3360.01  18577.26

### Length of the Time Period

In [6]:
df_comp.date.describe()

count           6269
unique          6269
top       07/01/1994
freq               1
Name: date, dtype: object

### This top value is arbitrary since each non-null value means 1 and so it randomly picks the top value

### From Text to Date

In [ ]:
#pd.to_datetime(df_comp.date) # gives error as it assumes the format being mm/dd/yyyy
# but our data is in dd/mm/yyyy format

In [42]:
df_comp.date = pd.to_datetime(df_comp.date , dayfirst=True) # makes the format yyyy/mm/dd which is the best format to manipulate

In [43]:
df_comp.head()

        date     spx      dax     ftse    nikkei
0 1994-01-07  469.90  2224.95  3445.98  18124.01
1 1994-01-10  475.27  2225.00  3440.58  18443.44
2 1994-01-11  474.13  2228.10  3413.77  18485.25
3 1994-01-12  474.17  2182.06  3372.02  18793.88
4 1994-01-13  472.47  2142.37  3360.01  18577.26

### Setting the Index

In [44]:
df_comp.set_index('date',inplace=True)

In [45]:
df_comp.head()

               spx      dax     ftse    nikkei
date
1994-01-07  469.90  2224.95  3445.98  18124.01
1994-01-10  475.27  2225.00  3440.58  18443.44
1994-01-11  474.13  2228.10  3413.77  18485.25
1994-01-12  474.17  2182.06  3372.02  18793.88
1994-01-13  472.47  2142.37  3360.01  18577.26

In [18]:
df_comp.loc['2018']

                    spx       dax         ftse    nikkei
date
2018-01-02  2695.809772  12871.39  7648.096000  22764.94
2018-01-03  2713.061006  12978.21  7671.107761  22764.94
2018-01-04  2723.992595  13167.89  7695.882659  23506.33
2018-01-05  2743.147773  13319.64  7724.218086  23714.53
2018-01-08  2747.710233  13367.78  7696.513071  23714.53
2018-01-09  2751.285249  13385.59  7731.020101  23849.99
2018-01-10  2748.225490  13281.34  7748.511845  23788.20
2018-01-11  2767.558142  13202.90  7762.941268  23710.43
2018-01-12  2786.244143  13245.03  7778.637689  23653.82
2018-01-15  2786.244143  13200.51  7769.139189  23714.88
2018-01-16  2776.420024  13246.33  7755.931441  23951.81
2018-01-17  2802.555574  13183.96  7725.432076  23868.34
2018-01-18  2798.030257  13281.43  7700.963484  23763.37
2018-01-19  2810.302683  13434.45  7730.787919  23808.06
2018-01-22  2832.974100  13463.69  7715.441534  23816.33
2018-01-23  2839.130362  13559.60  7731.827774  24124.15
2018-01-24  2837.544008  13414.74  7643.428966  23940.78
2018-01-25  2839.253031  13298.36  7615.839954  23669.49
2018-01-26  2872.867839  13340.17  7665.541292  23631.88
2018-01-29  2853.528411  13324.48  7671.533300  23629.34

### Setting the Desired Frequency

In [19]:
# we use .asfreq() with alphabet like 'd'-> daily, 'w'-> weekly, 'a'-> annually, 'h'-> hourly, 'm'-> monthly

In [21]:
df_comp = df_comp.asfreq('D')
df_comp

                    spx       dax         ftse    nikkei
date
1994-01-07   469.900000   2224.95  3445.980000  18124.01
1994-01-08          NaN       NaN          NaN       NaN
1994-01-09          NaN       NaN          NaN       NaN
1994-01-10   475.270000   2225.00  3440.580000  18443.44
1994-01-11   474.130000   2228.10  3413.770000  18485.25
...                 ...       ...          ...       ...
2018-01-25  2839.253031  13298.36  7615.839954  23669.49
2018-01-26  2872.867839  13340.17  7665.541292  23631.88
2018-01-27          NaN       NaN          NaN       NaN
2018-01-28          NaN       NaN          NaN       NaN
2018-01-29  2853.528411  13324.48  7671.533300  23629.34

[8789 rows x 4 columns]

In [46]:
df_comp =  df_comp.asfreq('B') # makes the frequency of the data acc to business days 
df_comp

                    spx       dax         ftse    nikkei
date
1994-01-07   469.900000   2224.95  3445.980000  18124.01
1994-01-10   475.270000   2225.00  3440.580000  18443.44
1994-01-11   474.130000   2228.10  3413.770000  18485.25
1994-01-12   474.170000   2182.06  3372.020000  18793.88
1994-01-13   472.470000   2142.37  3360.010000  18577.26
...                 ...       ...          ...       ...
2018-01-23  2839.130362  13559.60  7731.827774  24124.15
2018-01-24  2837.544008  13414.74  7643.428966  23940.78
2018-01-25  2839.253031  13298.36  7615.839954  23669.49
2018-01-26  2872.867839  13340.17  7665.541292  23631.88
2018-01-29  2853.528411  13324.48  7671.533300  23629.34

[6277 rows x 4 columns]

### Handling Missing Values

In [47]:
# To check if the missing values are there in the dataset , we already used .isna().sum() to find the total missing values
df_comp.isna().sum()

# we see that there are 8 missing values to each column!

spx       8
dax       8
ftse      8
nikkei    8
dtype: int64

In [54]:
# To handle these missing values, we can fill them using a method .ffill()' and 'bfill()' / or any other value'
df_comp.spx = df_comp.spx.ffill()

 # This code filled the missing values by the one previous day value !!
 # if bfill was used, then it would have filled the nan value by the forward day value
 # we can also fill by using any expression like finding mean, median, mode etc.

In [50]:
df_comp.isna().sum() # This code filled the missing values by the one previous day value !!

spx       0
dax       8
ftse      8
nikkei    8
dtype: int64

In [51]:
df_comp.ftse = df_comp.ftse.bfill() # backward fill -> fills the nan by one ahead data
df_comp.dax = df_comp.dax.fillna(df_comp.dax.mean()) # mean fill -> fills the nan by the columns mean value (NOT GOOD IDEA FOR TIMEDATA)

### Simplifying the Dataset

In [55]:
# creating a new column having the same value as S&P 500 Data
df_comp['market_value'] = df_comp.spx
df_comp.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 6277 entries, 1994-01-07 to 2018-01-29
Freq: B
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   spx           6277 non-null   float64
 1   dax           6277 non-null   float64
 2   ftse          6277 non-null   float64
 3   nikkei        6269 non-null   float64
 4   market_value  6277 non-null   float64
dtypes: float64(5)
memory usage: 294.2 KB

In [56]:
df_comp.describe()

               spx           dax         ftse        nikkei  market_value
count  6277.000000   6277.000000  6277.000000   6269.000000   6277.000000
mean   1288.642547   6080.063363  5423.690398  14597.055700   1288.642547
std     487.868210   2752.604984  1145.568370   4043.122953    487.868210
min     438.920000   1911.700000  2876.600000   7054.980000    438.920000
25%     992.715221   4070.460000  4487.880000  10709.290000    992.715221
50%    1233.761241   5774.380000  5663.300000  15028.170000   1233.761241
75%    1460.250000   7442.660000  6304.630175  17860.470000   1460.250000
max    2872.867839  13559.600000  7778.637689  24124.150000   2872.867839

In [57]:
# deleting/ removing the columns using del method

del df_comp['spx'], df_comp['ftse'], df_comp['dax'], df_comp['nikkei']

In [58]:
df_comp.describe()

       market_value
count   6277.000000
mean    1288.642547
std      487.868210
min      438.920000
25%      992.715221
50%     1233.761241
75%     1460.250000
max     2872.867839

### Splitting the Data

In [ ]:
size = int(len(df_comp)*0.8) # we find the index at which upto 80% data lies.

In [62]:
size

5021

In [ ]:
df_train = df_comp.iloc[:size] # we split the dataframe using iloc 
df_test = df_comp.iloc[size:]

In [65]:
print(df_train.tail())
df_test.head()

            market_value
date
2013-04-01   1562.173837
2013-04-02   1570.252238
2013-04-03   1553.686978
2013-04-04   1559.979316
2013-04-05   1553.278930

            market_value
date
2013-04-08   1563.071269
2013-04-09   1568.607909
2013-04-10   1587.731827
2013-04-11   1593.369863
2013-04-12   1588.854623

In [68]:
df = pd.read_csv('index2026.csv')

In [74]:
df.set_index('Ticker',inplace=True)

In [77]:
df.index.name = 'Date'

In [1]:
df.head()

NameError: name 'df' is not defined